#!/usr/bin/env python3
"""Download Hind (SIL OFL 1.1) from Google Fonts and write self-hosted @font-face rules.

Run from anywhere: python3 scripts/fetch-fonts.py
Writes static/fonts/hind/*.woff2, static/fonts/hind/OFL.txt, static/fonts/hind/SHA256SUMS
and assets/css/fonts.css.

The response is not trusted blindly: font files may only come from fonts.gstatic.com,
must be WOFF2, and every value copied into fonts.css is validated. SHA256SUMS records
the committed files (scripts/checks/docs.py verifies them), so any change to the font
files shows up in review; the script lists files whose hash changed.
"""
import hashlib
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS_URL = "https://fonts.googleapis.com/css2?family=Hind:wght@300;400;500;600;700&display=swap"
OFL_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/hind/OFL.txt"
# A modern browser UA makes Google Fonts serve woff2 with unicode-range subsets.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
SUBSETS = ("latin", "latin-ext")
FONT_HOST = "https://fonts.gstatic.com/"
UNICODE_RANGE = re.compile(r"^U\+[0-9A-Fa-f?]+(-[0-9A-Fa-f]+)?(, U\+[0-9A-Fa-f?]+(-[0-9A-Fa-f]+)?)*$")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def read_sums(path):
    sums = {}
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                digest, _, name = line.strip().partition("  ")
                sums[name] = digest
    return sums


def main():
    css = get(CSS_URL).decode()
    font_dir = os.path.join(ROOT, "static", "fonts", "hind")
    os.makedirs(font_dir, exist_ok=True)
    sums_path = os.path.join(font_dir, "SHA256SUMS")
    old_sums = read_sums(sums_path)
    new_sums = {}
    rules = []
    for subset, block in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S):
        if subset not in SUBSETS:
            continue
        weight = re.search(r"font-weight: (\d+);", block).group(1)
        url = re.search(r"src: url\((.*?)\)", block).group(1)
        unicode_range = re.search(r"unicode-range: (.*?);", block).group(1)
        if weight not in ("300", "400", "500", "600", "700"):
            raise SystemExit(f"unexpected font-weight {weight!r}")
        if not url.startswith(FONT_HOST):
            raise SystemExit(f"refusing to download a font from outside {FONT_HOST}: {url!r}")
        if not UNICODE_RANGE.match(unicode_range):
            raise SystemExit(f"unexpected unicode-range {unicode_range!r}")
        data = get(url)
        if not data.startswith(b"wOF2"):
            raise SystemExit(f"{url} is not a WOFF2 file")
        name = f"hind-{weight}-{subset}.woff2"
        new_sums[name] = hashlib.sha256(data).hexdigest()
        with open(os.path.join(font_dir, name), "wb") as fh:
            fh.write(data)
        rules.append(
            "@font-face {\n"
            '  font-family: "Hind";\n'
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f'  src: url("../fonts/hind/{name}") format("woff2");\n'
            f"  unicode-range: {unicode_range};\n"
            "}\n"
        )
    if len(rules) != 10:
        raise SystemExit(f"expected 10 font files (5 weights x 2 subsets), got {len(rules)}")
    with open(os.path.join(font_dir, "OFL.txt"), "wb") as fh:
        fh.write(get(OFL_URL))
    with open(sums_path, "w", encoding="utf-8") as fh:
        fh.writelines(f"{new_sums[n]}  {n}\n" for n in sorted(new_sums))
    changed = sorted(n for n in new_sums if old_sums.get(n) != new_sums[n])
    if old_sums and changed:
        print("font files changed since the last fetch (review before committing):\n  " + "\n  ".join(changed))
    header = ("/* Hind by Indian Type Foundry, SIL Open Font License 1.1 (static/fonts/hind/OFL.txt).\n"
              "   Generated by scripts/fetch-fonts.py; do not edit by hand. */\n")
    os.makedirs(os.path.join(ROOT, "assets", "css"), exist_ok=True)
    with open(os.path.join(ROOT, "assets", "css", "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(rules))
    print(f"wrote {len(rules)} font files to {font_dir}")


if __name__ == "__main__":
    main()
